.TH GCOV 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
gcov \- test coverage program for GNU CC
.SH SYNOPSIS
.B gcov
.I "[-b] [-v] [-n] [-l] [-f] [-o directory] sourcefile"
.br
.SH "DESCRIPTION"
This manual page documents briefly the
.BR gcov
command.
This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.PP
.B gcov
is a test coverage program.  Use it in concert with GNU
CC to analyze your programs to help create more efficient, faster
running code.  You can use gcov as a profiling tool to help
discover where your optimization efforts will best affect your code.  You
can also use gcov along with the other profiling tool,
.B gprof
, to assess which parts of your code use the greatest amount
of computing time.
.SH "SEE ALSO"
The program is documented fully by
.IR "gcc: The GNU C compiler.",
available via the Info system.  The documentation for genclass can be
found in the subsection "Gcov", under "a GNU CC test coverage program".
.SH AUTHOR
This manual page was written by the egcs maintainers for the Debian
GNU/Linux system.
